//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DuongTrang.Core.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Book
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Book()
        {
            this.Images = new HashSet<Image>();
        }
    
        public System.Guid BookID { get; set; }
        public string BookCode { get; set; }
        public string BookName { get; set; }
        public string Author { get; set; }
        public Nullable<System.Guid> CompanyPublishID { get; set; }
        public Nullable<System.DateTime> YearPublish { get; set; }
        public System.Guid KindID { get; set; }
        public System.Guid LanguageID { get; set; }
        public System.Guid CategoryID { get; set; }
        public Nullable<decimal> Price { get; set; }
        public string Content { get; set; }
        public Nullable<System.DateTime> AddDate { get; set; }
        public System.Guid CreateBy { get; set; }
        public string Keyword { get; set; }
        public bool IsDelete { get; set; }
        public Nullable<int> Remaining { get; set; }
    
        public virtual Category Category { get; set; }
        public virtual Company Company { get; set; }
        public virtual Kind Kind { get; set; }
        public virtual Language Language { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Image> Images { get; set; }
    }
}
