//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DuongTrang.Core.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Borrow
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Borrow()
        {
            this.BorrowDetails = new HashSet<BorrowDetail>();
        }
    
        public System.Guid BorrowID { get; set; }
        public Nullable<System.Guid> CardReaderID { get; set; }
        public Nullable<System.DateTime> DateBorrow { get; set; }
        public Nullable<int> AmountTotal { get; set; }
        public Nullable<System.Guid> CreateBy { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public Nullable<bool> IsDelete { get; set; }
        public Nullable<int> PendingStatusID { get; set; }
        public string BorrowCode { get; set; }
        public Nullable<System.Guid> AcceptBy { get; set; }
        public System.DateTime TimeToGet { get; set; }
        public Nullable<System.DateTime> DateExpried { get; set; }
    
        public virtual CardReader CardReader { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BorrowDetail> BorrowDetails { get; set; }
        public virtual PendingStatu PendingStatu { get; set; }
    }
}
