//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DuongTrang.Core.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BorrowDetailLog
    {
        public System.Guid ID { get; set; }
        public System.Guid BorrowDetailID { get; set; }
        public System.Guid BookID { get; set; }
        public Nullable<System.DateTime> DateExpried { get; set; }
        public System.Guid PendingStatusID { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public Nullable<System.Guid> CreateBy { get; set; }
        public Nullable<bool> IsDelete { get; set; }
    }
}
