//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DuongTrang.Core.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DATNEntities : DbContext
    {
        public DATNEntities()
            : base("name=DATNEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<C__MigrationHistory> C__MigrationHistory { get; set; }
        public virtual DbSet<AspNetRole> AspNetRoles { get; set; }
        public virtual DbSet<AspNetUserClaim> AspNetUserClaims { get; set; }
        public virtual DbSet<AspNetUserLogin> AspNetUserLogins { get; set; }
        public virtual DbSet<AspNetUser> AspNetUsers { get; set; }
        public virtual DbSet<Book> Books { get; set; }
        public virtual DbSet<Borrow> Borrows { get; set; }
        public virtual DbSet<BorrowDetail> BorrowDetails { get; set; }
        public virtual DbSet<BorrowDetailLog> BorrowDetailLogs { get; set; }
        public virtual DbSet<CardReader> CardReaders { get; set; }
        public virtual DbSet<Category> Categories { get; set; }
        public virtual DbSet<ChildMenu> ChildMenus { get; set; }
        public virtual DbSet<Company> Companies { get; set; }
        public virtual DbSet<Faculty> Faculties { get; set; }
        public virtual DbSet<Image> Images { get; set; }
        public virtual DbSet<Infringe> Infringes { get; set; }
        public virtual DbSet<Job> Jobs { get; set; }
        public virtual DbSet<Kind> Kinds { get; set; }
        public virtual DbSet<Language> Languages { get; set; }
        public virtual DbSet<Level> Levels { get; set; }
        public virtual DbSet<Menu> Menus { get; set; }
        public virtual DbSet<PendingStatu> PendingStatus { get; set; }
        public virtual DbSet<Reader> Readers { get; set; }
        public virtual DbSet<Return> Returns { get; set; }
        public virtual DbSet<Role_Menu> Role_Menu { get; set; }
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
        public virtual DbSet<TrainingSystem> TrainingSystems { get; set; }
    }
}
