//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DuongTrang.Core.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Image
    {
        public System.Guid ID { get; set; }
        public Nullable<System.Guid> BookID { get; set; }
        public string Image1 { get; set; }
        public Nullable<int> Size { get; set; }
    
        public virtual Book Book { get; set; }
    }
}
