//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DuongTrang.Core.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PendingStatu
    {
        public System.Guid PendingStatusID { get; set; }
        public string PendingStatusName { get; set; }
        public Nullable<bool> IsDelete { get; set; }
    }
}
