//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DuongTrang.Core.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Return
    {
        public System.Guid ReturnID { get; set; }
        public Nullable<System.Guid> CardReaderID { get; set; }
        public Nullable<System.DateTime> DateReturn { get; set; }
        public string ReturnStatus { get; set; }
        public Nullable<System.Guid> BookID { get; set; }
        public Nullable<bool> IsDelete { get; set; }
    
        public virtual Reader Reader { get; set; }
    }
}
