//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DuongTrang.Core.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Role_Menu
    {
        public System.Guid ID { get; set; }
        public string RoleId { get; set; }
        public Nullable<System.Guid> MenuID { get; set; }
        public Nullable<bool> IsDelete { get; set; }
    
        public virtual AspNetRole AspNetRole { get; set; }
        public virtual Menu Menu { get; set; }
    }
}
